// DdraigBench — 方言公共实现（字面量渲染 + 默认分页）

using System.Globalization;

namespace DdraigBench.Core.Dialects;

public abstract class SqlDialectBase : ISqlDialect
{
    public abstract string QuoteIdentifier(string name);

    public virtual string BuildPaging(int limit, long offset) => $"LIMIT {limit} OFFSET {offset}";

    public virtual string FormatLiteral(object? value) => value switch
    {
        null or DBNull => "NULL",
        bool b => b ? "TRUE" : "FALSE",
        byte[] bytes => FormatBinary(bytes),
        DateTime dt => Quote(dt.ToString("yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture)),
        DateTimeOffset dto => Quote(dto.ToString("yyyy-MM-dd HH:mm:ss.fffzzz", CultureInfo.InvariantCulture)),
        TimeSpan ts => Quote(ts.ToString()),
        string s => Quote(s),
        char c => Quote(c.ToString()),
        Guid g => Quote(g.ToString()),
        sbyte or byte or short or ushort or int or uint or long or ulong
            or float or double or decimal
            => Convert.ToString(value, CultureInfo.InvariantCulture)!,
        _ => Quote(Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty),
    };

    protected static string Quote(string text) => $"'{text.Replace("'", "''")}'";

    /// <summary>默认按标准 SQL / PostgreSQL 语义：GENERATED BY DEFAULT AS IDENTITY。</summary>
    public virtual string IdentityClause => "GENERATED BY DEFAULT AS IDENTITY";

    public virtual string BuildIdentityColumn(string quotedName, string type, bool nullable) =>
        nullable
            ? $"{quotedName} {type} {IdentityClause} PRIMARY KEY"
            : $"{quotedName} {type} NOT NULL {IdentityClause} PRIMARY KEY";

    protected abstract string FormatBinary(byte[] bytes);
}
