// DdraigBench — DDL 生成器单测（手搭元数据 + 真实 SQLite 往返）

using DdraigBench.Core.Connections;
using DdraigBench.Core.Dialects;
using DdraigBench.Core.Metadata;
using DdraigBench.Core.Sessions;
using FreeSql;
using FreeSql.DatabaseModel;
using DbColumnInfo = FreeSql.DatabaseModel.DbColumnInfo;

namespace DdraigBench.Test;

public sealed class DdlGeneratorTests
{
    private static DdlGenerator Sqlite => new(SqliteDialect.Instance);

    private static DbColumnInfo Column(
        string name,
        string type,
        bool isPrimary = false,
        bool isNullable = true,
        bool isIdentity = false,
        string? defaultValue = null,
        string? comment = null) =>
        new()
        {
            Name = name,
            DbTypeText = type,
            IsPrimary = isPrimary,
            IsNullable = isNullable,
            IsIdentity = isIdentity,
            DefaultValue = defaultValue,
            Comment = comment,
        };

    [Fact]
    public void Single_identity_primary_key_is_inline()
    {
        var table = new DbTableInfo { Name = "t1" };
        table.Columns.Add(Column("id", "INTEGER", isPrimary: true, isNullable: false, isIdentity: true));
        table.Columns.Add(Column("name", "TEXT", comment: "用户名"));

        Assert.Equal(
            "CREATE TABLE \"t1\" (\n"
            + "  \"id\" INTEGER PRIMARY KEY AUTOINCREMENT,\n"
            + "  \"name\" TEXT -- 用户名\n"
            + ");\n",
            Sqlite.CreateTable(table));
    }

    [Fact]
    public void Composite_primary_key_becomes_table_constraint()
    {
        var table = new DbTableInfo { Name = "t2" };
        table.Columns.Add(Column("a", "INTEGER", isPrimary: true, isNullable: false));
        table.Columns.Add(Column("b", "INTEGER", isPrimary: true, isNullable: false));

        var ddl = Sqlite.CreateTable(table);

        Assert.Contains("CONSTRAINT \"PK_t2\" PRIMARY KEY (\"a\", \"b\")", ddl);
        Assert.DoesNotContain("PRIMARY KEY AUTOINCREMENT", ddl);
    }

    [Fact]
    public void Defaults_comments_indexes_and_foreign_keys_are_emitted()
    {
        var parent = new DbTableInfo { Name = "parent" };
        parent.Columns.Add(Column("pid", "INTEGER", isPrimary: true, isNullable: false));

        var table = new DbTableInfo { Schema = "main", Name = "child", Comment = "子表" };
        var parentId = Column("pid", "INTEGER", isNullable: false);
        table.Columns.Add(parentId);
        table.Columns.Add(Column("qty", "INTEGER", isNullable: false, defaultValue: "0", comment: "数量"));

        var foreign = new DbForeignInfo
        {
            ReferencedTable = parent,
            Columns = { parentId },
            ReferencedColumns = { parent.Columns[0] },
        };
        table.ForeignsDict["FK_child_pid"] = foreign;

        var index = new DbIndexInfo { Name = "ix_child_qty", IsUnique = true };
        index.Columns.Add(new DbIndexColumnInfo { Column = table.Columns[1], IsDesc = true });
        table.IndexesDict["ix_child_qty"] = index;
        table.IndexesDict["sqlite_autoindex_child_1"] = new DbIndexInfo { Name = "sqlite_autoindex_child_1" };

        var ddl = Sqlite.CreateTable(table);

        Assert.StartsWith("-- 子表\nCREATE TABLE \"main\".\"child\" (\n", ddl);
        Assert.Contains("\"qty\" INTEGER NOT NULL DEFAULT 0 -- 数量", ddl);
        Assert.Contains("CONSTRAINT \"FK_child_pid\" FOREIGN KEY (\"pid\") REFERENCES \"parent\" (\"pid\")", ddl);
        Assert.Contains("CREATE UNIQUE INDEX \"ix_child_qty\" ON \"main\".\"child\" (\"qty\" DESC);", ddl);
        Assert.DoesNotContain("sqlite_autoindex", ddl);
    }

    [Fact]
    public void Mysql_uses_backticks_and_mysql_identity_order()
    {
        var table = new DbTableInfo { Name = "t1" };
        table.Columns.Add(Column("id", "int", isPrimary: true, isNullable: false, isIdentity: true));

        var ddl = new DdlGenerator(MySqlDialect.Instance).CreateTable(table);

        Assert.Equal("CREATE TABLE `t1` (\n  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY\n);\n", ddl);
    }

    [Fact]
    public void Postgresql_uses_identity_clause()
    {
        var table = new DbTableInfo { Schema = "public", Name = "t1" };
        table.Columns.Add(Column("id", "integer", isPrimary: true, isNullable: false, isIdentity: true));

        var ddl = new DdlGenerator(PostgreSqlDialect.Instance).CreateTable(table);

        Assert.Equal(
            "CREATE TABLE \"public\".\"t1\" (\n  \"id\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY\n);\n",
            ddl);
    }

    [Fact]
    public void View_gets_placeholder_with_columns()
    {
        var view = new DbTableInfo { Name = "v1", Type = DbTableType.VIEW };
        view.Columns.Add(Column("id", "INTEGER"));

        var ddl = Sqlite.CreateTable(view);

        Assert.Contains("-- 视图：\"v1\"", ddl);
        Assert.Contains("--   id INTEGER", ddl);
        Assert.DoesNotContain("CREATE TABLE", ddl);
    }

    [Fact]
    public async Task Real_sqlite_table_round_trips_into_ddl()
    {
        using var db = new TempSqliteDatabase();
        using var fsql = db.CreateFsql();
        fsql.Ado.ExecuteNonQuery(
            """
            CREATE TABLE orders (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                qty INTEGER NOT NULL DEFAULT 0
            );
            CREATE INDEX ix_orders_title ON orders (title);
            """);

        var infos = fsql.DbFirst.GetTablesByDatabase("main");
        var orders = infos.Single(t => t.Name == "orders");

        var ddl = Sqlite.CreateTable(orders);

        Assert.Contains("CREATE TABLE \"orders\" (", ddl);
        // 已知缺口：SQLite 的 AUTOINCREMENT 不在声明类型里，IDbFirst 不会填 IsIdentity（见 AGENTS.md §6.2）
        Assert.Contains("\"id\" INTEGER NOT NULL PRIMARY KEY", ddl);
        Assert.Contains("\"qty\" INTEGER NOT NULL DEFAULT 0", ddl);
        Assert.Contains("CREATE INDEX \"ix_orders_title\" ON \"orders\" (\"title\");", ddl);

        // 生成的 DDL 必须能被同一个库重新执行（方言正确性的端到端校验）
        fsql.Ado.ExecuteNonQuery("DROP TABLE orders");
        fsql.Ado.ExecuteNonQuery(ddl);

        await Task.CompletedTask;
    }
}
